export const userData = {
  status: 'Success',
  message: 'Users were fetched successfully',
  data: [
    {
      id: '64a2be96016941a48f4ad1ae',
      firstName: 'Vinay',
      lastName: 'Jeengar',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'vinay@reshield.io',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'admin',
      userJoined: true,
      roles: [
        {
          id: '64a2bf02016941a48f4ad1b0',
          name: 'Lead Engineer',
        },
      ],
      permissions: null,
    },
    {
      id: '64a2be96016941a48f4ad1af',
      firstName: 'Aakash',
      lastName: 'Bhardwaj',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'aakash@reshield.io',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'admin',
      userJoined: true,
      roles: [
        {
          id: '64a2bf02016941a48f4ad1b0',
          name: 'Lead Engineer',
        },
      ],
      permissions: [
        {
          id: 'cecd59ed-9a32-4d84-8efd-dad0ec323fac',
          name: 'aws-stage:read',
        },
      ],
    },
    {
      id: '64ad35793ee06b488d38149a',
      firstName: 'Varun',
      lastName: 'Verma',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'varun@observe.ai',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'user',
      userJoined: false,
      roles: [
        {
          id: '64a2bf02016941a48f4ad1b0',
          name: 'Lead Engineer',
        },
      ],
      permissions: null,
    },
    {
      id: '64ba78eeb0167b8ae194da54',
      firstName: 'Aakash',
      lastName: 'Approver ',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'aakash.bhardwaj90@gmail.com',
      mobileNumber: '6665789675',
      managedBy: 'SSO',
      appRole: 'user',
      userJoined: true,
      roles: [
        {
          id: '64a2bf02016941a48f4ad1b1',
          name: 'Engineering Manager',
        },
      ],
      permissions: [
        {
          id: 'fa5009c4-6f71-4dd4-92d0-33252ffee740',
          name: 'orders-prod:write',
        },
      ],
    },
    {
      id: '64ba85269a48db5d779c9233',
      firstName: 'Vinay',
      lastName: 'Approver ',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'vinayjeengar8@gmail.com',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'user',
      userJoined: true,
      roles: [
        {
          id: '64a2bf02016941a48f4ad1b1',
          name: 'Engineering Manager',
        },
      ],
      permissions: null,
    },
    {
      id: '651a4eacddb0fad57d0c2db7',
      firstName: 'random-ab',
      lastName: 'test',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'aakash.bhardwaj90@gmail.com',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'user',
      userJoined: false,
      roles: [
        {
          id: '64a2bf02016941a48f4ad1b0',
          name: 'Lead Engineer',
        },
      ],
      permissions: null,
    },
    {
      id: '651a50dbddb0fad57d0c2db9',
      firstName: 'random-ab',
      lastName: 'test-2',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'aakash101@reshield.io',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'admin',
      userJoined: false,
      roles: [
        {
          id: '64a2bf02016941a48f4ad1b0',
          name: 'Lead Engineer',
        },
      ],
      permissions: null,
    },
    {
      id: '651a51b5ddb0fad57d0c2dbb',
      firstName: 'aakash',
      lastName: 'test3',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'aakash.bhardwaj904@gmail.com',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'user',
      userJoined: false,
      roles: [
        {
          id: '64a2bf02016941a48f4ad1b0',
          name: 'Lead Engineer',
        },
      ],
      permissions: null,
    },
    {
      id: '651a5450ddb0fad57d0c2dbd',
      firstName: 'aakash',
      lastName: 'test4',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'aakash.bhardwaj902@gmail.com',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'user',
      userJoined: true,
      roles: [
        {
          id: '64a2bf02016941a48f4ad1b0',
          name: 'Lead Engineer',
        },
      ],
      permissions: null,
    },
    {
      id: '6582ec5fd9f7852b56568942',
      firstName: 'aavde',
      lastName: '2a1',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'vinayjeengasdar8@gmail.com',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'user',
      userJoined: false,
      roles: null,
      permissions: null,
    },
    {
      id: '6583f549d9f7852b5656895e',
      firstName: 'test',
      lastName: '',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'test@gmail.com',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'user',
      userJoined: false,
      roles: null,
      permissions: null,
    },
    {
      id: '6596a2bfd9f7852b565689b1',
      firstName: 'Yashveer',
      lastName: 'Singh',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'yashveer@reshield.io',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'admin',
      userJoined: true,
      roles: [
        {
          id: '64a2bf02016941a48f4ad1b1',
          name: 'Engineering Manager',
        },
      ],
      permissions: null,
    },
    {
      id: '659f932972c02427e57296ab',
      firstName: 'vijay',
      lastName: '',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'vijay@joyship.in',
      mobileNumber: '',
      managedBy: 'Google SSO',
      appRole: 'admin',
      userJoined: true,
      roles: null,
      permissions: null,
    },
    {
      id: '65a7ae07e1b19cfbd05f99cd',
      firstName: 'Yashveer',
      lastName: 'Singh',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'yashveer@uixlabs.in',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'user',
      userJoined: true,
      roles: [
        {
          id: '64d0d90a53b015853b55e1c3',
          name: 'Developer',
        },
      ],
      permissions: null,
    },
    {
      id: '65b3cf957f8c56b3a4318f22',
      firstName: 'some',
      lastName: 'test',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'test@reshield.io',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'user',
      userJoined: false,
      roles: null,
      permissions: null,
    },
    {
      id: '65b3cfc57f8c56b3a4318f25',
      firstName: 'somethingthing',
      lastName: 'test',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'founders@reshield.io',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'user',
      userJoined: false,
      roles: null,
      permissions: null,
    },
    {
      id: '65c31ff88f9740b4501c1d5a',
      firstName: 'Suraj Singh',
      lastName: 'Rajput',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: 'professor@uixlabs.in',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'admin',
      userJoined: true,
      roles: [
        {
          id: '64a2bf02016941a48f4ad1b0',
          name: 'Lead Engineer',
        },
      ],
      permissions: null,
    },
    {
      id: '65eb0cbefefa52eb9de9d668',
      firstName: 'Suraj ',
      lastName: 'Approver',
      accountId: '64a2be83016941a48f4ad1ad',
      emailId: '00suraj.sig@gmail.com',
      mobileNumber: '',
      managedBy: 'Manual',
      appRole: 'admin',
      userJoined: false,
      roles: [
        {
          id: '64a2bf02016941a48f4ad1b0',
          name: 'Lead Engineer',
        },
      ],
      permissions: [
        {
          id: 'fa5009c4-6f71-4dd4-92d0-33252ffee740',
          name: 'orders-prod:write',
        },
        {
          id: '2f34ef88-67d3-88b8-a515-9d834c0c05eb',
          name: 'orders-prod:read',
        },
      ],
    },
  ],
};

export const roleData = {
  status: 'Success',
  message: 'Roles were fetched successfully',
  data: [
    {
      id: '64a2bf02016941a48f4ad1b0',
      name: 'Lead Engineer',
      managedBy: 'Manual',
      permissions: [
        {
          id: '2f34ef88-67d3-88b8-a515-9d834c0c05eb',
          name: 'orders-prod:read',
        },
        {
          id: '2f34ef88-67d3-88b8-a515-9d834c0c05ev',
          name: 'search-prod:read',
        },
        {
          id: 'd43b04af-ec1e-44d9-bc7b-45e3880a0086',
          name: 'payments-prod:read',
        },
        {
          id: '2f34ef88-67d3-4ab8-a515-9d834c0c05ec',
          name: 'invoice-prod:read',
        },
        {
          id: 'fa5009c4-6f71-4ee4-92d0-33252ffee741',
          name: 'invoice-prod:write',
        },
        {
          id: 'd43b04af-ec1e-88d9-bc7b-45e31b0a0086',
          name: 'payments-prod:pci-custom',
        },
        {
          id: 'b1bfe7da-b7e3-48ca-a6aa-c7c630f2eb9e',
          name: 'payments-prod:replicaset',
        },
        {
          id: 'cecd59ed-9a32-4d84-8efd-dad0ec323fac',
          name: 'aws-stage:read',
        },
        {
          id: '0f64cc3a-959d-4dbd-83e3-2c3d9be426fa',
          name: 'aws-stage:write',
        },
        {
          id: '3e95eefc-629e-4684-917a-57e4b0bc5616',
          name: 'test-resource-db:read',
        },
      ],
    },
    {
      id: '64a2bf02016941a48f4ad1b1',
      name: 'Engineering Manager',
      managedBy: 'Manual',
      permissions: [
        {
          id: '76eb0d57-2d5c-415b-bb86-964b2850dc22',
          name: 'payments-prod:write',
        },
      ],
    },
    {
      id: '64d0d90a53b015853b55e1c3',
      name: 'Developer',
      managedBy: 'Manual',
      permissions: [
        {
          id: 'd43b04af-ec1e-88d9-bc7b-45e31b0a0086',
          name: 'payments-prod:pci-custom',
        },
      ],
    },
    {
      id: '659d0e7c38637f4bf8bcef2c',
      name: 'test',
      managedBy: 'Manual',
      permissions: [
        {
          id: 'db55620e-ac9b-4ffc-8f88-6cb431d2f06a',
          name: 'bigquery-test:data-read',
        },
        {
          id: 'd43b04af-ec1e-44d9-bc7b-45e3880a0086',
          name: 'payments-prod:read',
        },
      ],
    },
  ],
};

export const resourceData = {
  status: 'Success',
  message: 'Resources were fetched successfully',
  data: [
    {
      id: '64a2bf3b016941a48f4ad1b2',
      name: 'orders-prod',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'MongoDB',
      gatewayId: '657c31e6d6f6cbf4f813f607',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: '2f34ef88-67d3-88b8-a515-9d834c0c05eb',
          permissionName: 'read',
          credential: null,
          overridePort: 9467,
          defaultTtl: '24h',
          approvalConfig: {
            approverUserIds: ['65c31ff88f9740b4501c1d5a', '65eb0cbefefa52eb9de9d668'],
            approverRoleIds: null,
          },
          auditFilterConfig: {
            dbsToIgnore: ['test'],
            commandsToIgnore: [
              'ismaster',
              'collStats',
              'isMaster',
              'rolesInfo',
              'dbstats',
              'listCollections',
              'listDatabases',
              '',
              'hello',
            ],
          },
          granularControlType: 'EXCLUDE',
          granularControlValues: ['test_db.testCollection'],
        },
        {
          permissionId: 'fa5009c4-6f71-4dd4-92d0-33252ffee740',
          permissionName: 'write',
          credential: null,
          overridePort: 7742,
          defaultTtl: '24h',
          approvalConfig: {
            approverUserIds: ['65c31ff88f9740b4501c1d5a', '65eb0cbefefa52eb9de9d668'],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: null,
            commandsToIgnore: null,
          },
          granularControlType: '',
          granularControlValues: null,
        },
      ],
    },
    {
      id: '64a2bf3b016941a48f4ad1b3',
      name: 'payments-prod',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'MongoDB',
      gatewayId: '64d6280753b015853b55e1c7',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: 'd43b04af-ec1e-44d9-bc7b-45e3880a0086',
          permissionName: 'read',
          credential: null,
          overridePort: 8766,
          defaultTtl: '36h',
          approvalConfig: {
            approverUserIds: null,
            approverRoleIds: null,
          },
          auditFilterConfig: {
            dbsToIgnore: ['test'],
            commandsToIgnore: [
              'ismaster',
              'collStats',
              'isMaster',
              'rolesInfo',
              'dbstats',
              'listCollections',
              'listDatabases',
              '',
              'hello',
            ],
          },
          granularControlType: 'INCLUDE',
          granularControlValues: ['*:read'],
        },
        {
          permissionId: '76eb0d57-2d5c-415b-bb86-964b2850dc22',
          permissionName: 'write',
          credential: null,
          overridePort: 8889,
          defaultTtl: '24h',
          approvalConfig: {
            approverUserIds: ['64a2be96016941a48f4ad1ae', '65c31ff88f9740b4501c1d5a'],
            approverRoleIds: ['64a2bf02016941a48f4ad1b1'],
          },
          auditFilterConfig: {
            dbsToIgnore: null,
            commandsToIgnore: null,
          },
          granularControlType: '',
          granularControlValues: null,
        },
        {
          permissionId: 'd43b04af-ec1e-88d9-bc7b-45e31b0a0086',
          permissionName: 'custom',
          credential: null,
          overridePort: 5024,
          defaultTtl: '2d',
          approvalConfig: {
            approverUserIds: null,
            approverRoleIds: null,
          },
          auditFilterConfig: {
            dbsToIgnore: null,
            commandsToIgnore: null,
          },
          granularControlType: '',
          granularControlValues: null,
        },
        {
          permissionId: 'b1bfe7da-b7e3-48ca-a6aa-c7c630f2eb9e',
          permissionName: 'replicaset',
          credential: null,
          overridePort: 9413,
          defaultTtl: '12h',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: ['64a2bf02016941a48f4ad1b1'],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '64d0dfb453b015853b55e1c5',
      name: 'invoice-prod',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'PostgreSQL',
      gatewayId: '657c31e6d6f6cbf4f813f607',
      properties: null,
      filterTags: [
        {
          key: 'team',
          values: ['platform', 'app'],
        },
      ],
      permissions: [
        {
          permissionId: '2f34ef88-67d3-4ab8-a515-9d834c0c05ec',
          permissionName: 'read',
          credential: null,
          overridePort: 9591,
          defaultTtl: '24h',
          approvalConfig: {
            approverUserIds: null,
            approverRoleIds: null,
          },
          auditFilterConfig: {
            dbsToIgnore: null,
            commandsToIgnore: null,
          },
          granularControlType: '',
          granularControlValues: null,
        },
        {
          permissionId: 'fa5009c4-6f71-4ee4-92d0-33252ffee741',
          permissionName: 'write',
          credential: null,
          overridePort: 4051,
          defaultTtl: '24h',
          approvalConfig: {
            approverUserIds: null,
            approverRoleIds: null,
          },
          auditFilterConfig: {
            dbsToIgnore: null,
            commandsToIgnore: null,
          },
          granularControlType: '',
          granularControlValues: null,
        },
      ],
    },
    {
      id: '64d9d153b0167b8ae194da55',
      name: 'aws-stage',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'Cloud',
      subType: 'aws',
      gatewayId: '64d6280753b015853b55e1c7',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: 'cecd59ed-9a32-4d84-8efd-dad0ec323fac',
          permissionName: 'read',
          credential: null,
          overridePort: 0,
          defaultTtl: '12h',
          approvalConfig: {
            approverUserIds: ['64ba85269a48db5d779c9233'],
            approverRoleIds: null,
          },
          auditFilterConfig: {
            dbsToIgnore: null,
            commandsToIgnore: null,
          },
          granularControlType: '',
          granularControlValues: null,
        },
        {
          permissionId: '0f64cc3a-959d-4dbd-83e3-2c3d9be426fa',
          permissionName: 'write',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: ['64ba85269a48db5d779c9233'],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '64df65b2b0167b8ae194da56',
      name: 'search-prod',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'Elasticsearch',
      gatewayId: '657c31e6d6f6cbf4f813f607',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: '2f34ef88-67d3-88b8-a515-9d834c0c05ev',
          permissionName: 'read',
          credential: null,
          overridePort: 9333,
          defaultTtl: '24h',
          approvalConfig: {
            approverUserIds: null,
            approverRoleIds: null,
          },
          auditFilterConfig: {
            dbsToIgnore: null,
            commandsToIgnore: null,
          },
          granularControlType: '',
          granularControlValues: null,
        },
      ],
    },
    {
      id: '651a4862ddb0fad57d0c2db4',
      name: 'test-resource',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'Kubernetes',
      subType: 'eks',
      gatewayId: '64d6280753b015853b55e1c7',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: '2bb2bd9c-22bf-43fa-85fc-8dd56a5f9afd',
          permissionName: 'basic',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: '5861c619-9d19-48b9-818b-fa284f6e29f5',
          permissionName: 'asdasd',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '651a48a2ddb0fad57d0c2db6',
      name: 'test-resource-db',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'MongoDB',
      gatewayId: '657c31e6d6f6cbf4f813f607',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: '3e95eefc-629e-4684-917a-57e4b0bc5616',
          permissionName: 'read',
          credential: null,
          overridePort: 54678,
          defaultTtl: '12h',
          approvalConfig: {
            approverUserIds: null,
            approverRoleIds: null,
          },
          auditFilterConfig: {
            dbsToIgnore: ['test'],
            commandsToIgnore: [
              'ismaster',
              'collStats',
              'isMaster',
              'rolesInfo',
              'dbstats',
              'listCollections',
              'listDatabases',
              '',
              'hello',
            ],
          },
          granularControlType: 'EXCLUDE',
          granularControlValues: ['*:write'],
        },
      ],
    },
    {
      id: '652f8aa3500767ffac61becf',
      name: 'bigquery-test',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'BigQuery',
      gatewayId: '64d6280753b015853b55e1c7',
      properties: null,
      filterTags: [
        {
          key: 'env',
          values: ['prod'],
        },
      ],
      permissions: [
        {
          permissionId: 'db55620e-ac9b-4ffc-8f88-6cb431d2f06a',
          permissionName: 'data-read',
          credential: null,
          overridePort: 0,
          defaultTtl: '12h',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: ['64a2bf02016941a48f4ad1b1'],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'c10f233d-e6f3-41af-b365-d11e1321c332',
          permissionName: 'data-write',
          credential: null,
          overridePort: 0,
          defaultTtl: '3h',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: ['64a2bf02016941a48f4ad1b1'],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '659c038438637f4bf8bcef0d',
      name: 'test',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'MongoDB',
      gatewayId: '657c31e6d6f6cbf4f813f607',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: '9d6b26c3-5375-41f9-9801-c226af93146a',
          permissionName: 'test',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '659d0f0038637f4bf8bcef2e',
      name: 'mydb',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'MongoDB',
      gatewayId: '64d6280753b015853b55e1c7',
      properties: null,
      filterTags: [],
      permissions: null,
    },
    {
      id: '659d0f1638637f4bf8bcef30',
      name: 'mydb-def',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'MongoDB',
      gatewayId: '64d6280753b015853b55e1c7',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: 'fa7f9b19-69c4-4aaf-a22c-3d595764eef2',
          permissionName: 'read',
          credential: null,
          overridePort: 12312,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '659d0f5f38637f4bf8bcef34',
      name: 'pg-def',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'PostgreSQL',
      gatewayId: '64d6280753b015853b55e1c7',
      properties: null,
      filterTags: [],
      permissions: null,
    },
    {
      id: '659d0f8a38637f4bf8bcef36',
      name: 'g2-bq',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'BigQuery',
      gatewayId: '657c31e6d6f6cbf4f813f607',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: '5034ad0d-f03c-406d-a237-038e5095589a',
          permissionName: 'reads',
          credential: null,
          overridePort: 123,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '65a22b45a265ca7033f221b8',
      name: 'test',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'Cloud',
      subType: 'aws',
      gatewayId: '',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: 'd7b977b6-604a-4a66-a64d-661eea169a8d',
          permissionName: 'test',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'ba8372e4-e8c4-4aa0-8c0d-2d538fb5d0e9',
          permissionName: 'asdasd',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: '809b09fe-547d-459f-b84e-e83da94fa7cd',
          permissionName: 'twwtwtw',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '65a2473ea265ca7033f221be',
      name: 'aws-dev',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'Cloud',
      subType: 'aws',
      gatewayId: '64d6280753b015853b55e1c7',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: '29970b32-27c1-4f49-b554-6f90f88e1ccd',
          permissionName: '12',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'c61b6790-bf14-481c-9ed5-d34d9eb77563',
          permissionName: '34',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: '902b7024-20c5-4981-b92b-d25b2f9a8dfb',
          permissionName: '56',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'b241c825-fad9-4272-a7bd-5c2227677ad6',
          permissionName: '78',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'e683b8fa-66fe-4787-aaa4-de48d5fae462',
          permissionName: '99',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: '1eff5eba-7788-4a74-890b-477ad756a735',
          permissionName: '00',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '65f4330ed84212bedd93a942',
      name: 'testing',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'Kubernetes',
      subType: 'eks',
      gatewayId: '',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: 'e978c2d2-bbc1-4af5-83dd-b97179802ddb',
          permissionName: 'tests',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: '5c457c8b-2ded-476a-a0b6-6dd47a5be969',
          permissionName: 'tests22',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'ad01903b-2dc2-41a8-b72a-9ba1290519db',
          permissionName: 'test_123',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: '64b0c205-10b1-4c38-acf4-23cc07c36687',
          permissionName: '16',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '65fa9e99d84212bedd940319',
      name: 'test',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'Kubernetes',
      subType: 'eks',
      gatewayId: '',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: '1a808bdd-cccd-46e2-833b-5f2de0657aa3',
          permissionName: 'test345',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: '8fc266e7-b5af-4abe-8475-ea352f7d00bb',
          permissionName: 'tes123',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: '72896a54-7977-43cc-ade7-7f32a0325a0a',
          permissionName: 'tests2434',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'd7908ea0-1971-41cb-96e8-e2ecf93466aa',
          permissionName: 'hello',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: '31e699a2-439f-4d65-9ddf-16334c5261c1',
          permissionName: 'hehe',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: '999edb91-f542-4c65-97a1-90ebbf36aa8a',
          permissionName: 'test',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '65fc01acd84212bedd9404d6',
      name: 'hello',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'Cloud',
      subType: 'aws',
      gatewayId: '',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: '3690ef82-ba58-4872-a88a-a203376c8ba4',
          permissionName: 'testing123',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '65fd1fb2d84212bedd940531',
      name: '1234',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'MongoDB',
      gatewayId: '',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: 'f0e742db-0832-42e7-88fe-d42d9160f251',
          permissionName: '12',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'b122c945-c0bd-4ac5-9e8a-bf4cdd089a2e',
          permissionName: '34',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'a8e1b919-24fc-4bb4-bf2a-01976dfd2fcd',
          permissionName: 'test123',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'c73ea0eb-20cc-4927-9ce9-74d3c3861c8c',
          permissionName: 'test123',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: '090b5646-3784-4a47-901e-04c4e18cc29d',
          permissionName: 'hello',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'f042d88a-e675-46e3-b7b9-4b4da44f6620',
          permissionName: 'hqw12',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '65fd2009d84212bedd94053b',
      name: '1223',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'Cloud',
      subType: 'aws',
      gatewayId: '657c31e6d6f6cbf4f813f607',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: 'e0222baa-bec0-4917-bf26-75329645c238',
          permissionName: '12',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'c78957a3-159d-4f38-a9bb-cf44f27a9753',
          permissionName: '34',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'd10b87d8-4abb-4143-b27c-5831675bf085',
          permissionName: '56',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '65fd204bd84212bedd940545',
      name: '1234',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'Kubernetes',
      subType: 'eks',
      gatewayId: '657c31e6d6f6cbf4f813f607',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: '520a8d23-d4e6-484c-afe8-74f4898b6ecf',
          permissionName: '12',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'caeaf188-60f5-45d3-9903-2cb8099fbe40',
          permissionName: '234234',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: ['64a2bf02016941a48f4ad1b0'],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '65fd2b21d84212bedd940576',
      name: 'final-test',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'MongoDB',
      gatewayId: '64d6280753b015853b55e1c7',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: '6bc5048b-4b62-4e96-83c8-aa5549187904',
          permissionName: 'test123',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'fb4acd6d-79dd-4474-bb55-70cd96c9b8ee',
          permissionName: 'tes1231',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
    {
      id: '65fd3997d84212bedd94058d',
      name: '1221',
      accountId: '64a2be83016941a48f4ad1ad',
      type: 'DATA_SOURCE',
      subType: 'MongoDB',
      gatewayId: '64d6280753b015853b55e1c7',
      properties: null,
      filterTags: [],
      permissions: [
        {
          permissionId: '3d39153b-970c-4c24-b788-374258d15e21',
          permissionName: '12',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
        {
          permissionId: 'f64d3781-4ce5-4551-a1bf-f9027d7fe0d4',
          permissionName: '34',
          credential: null,
          overridePort: 0,
          defaultTtl: '',
          approvalConfig: {
            approverUserIds: [],
            approverRoleIds: [],
          },
          auditFilterConfig: {
            dbsToIgnore: [],
            commandsToIgnore: [],
          },
          granularControlType: '',
          granularControlValues: [],
        },
      ],
    },
  ],
};
